config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    namespace :dashboard do
      resources :decks
      resources :cards
      resources :users, only: [:new, :create, :edit, :update]

      put '/users/:id/set_current/:deck_id' => 'users#set_current_deck', :as => 'set_deck'
      root 'home#index'
      post 'home' => 'home#check'
    end

    namespace :home do
      resources :user_sessions, only: [:new, :create, :destroy]
      get 'login' => 'user_sessions#new', :as => :login
      post 'logout' => 'user_sessions#destroy', :as => :logout
    end
  end

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get '/' => 'dashboard/home#index'
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :cards
  validates :user, presence: true
  validates :name, presence: true
  validates_uniqueness_of :name, scope: :user_id
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  before_action :set_card, only: [:edit, :show, :update, :destroy]

  def index
    @cards = current_user.cards.all
  end

  def new
    @card = current_user.cards.new
  end

  def edit
  end

  def create
    @card = current_user.cards.new(cards_params)
    if @card.save
      redirect_to [:dashboard, @card]
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @card.update(cards_params)
      redirect_to [:dashboard, @card]
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to dashboard_cards_path
  end

  private

  def cards_params
    params.require(:card).permit(:original_text, :translated_text, :img_remote_url, :deck_id, :review_date)
  end

  def set_card
    @card = current_user.cards.find_by(id: params[:id])
    redirect_to dashboard_root_path unless @card
  end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  before_action :set_deck, only: [:edit, :show, :update, :destroy]

  def index
    @decks = current_user.decks.all
  end

  def new
    @deck = current_user.decks.new
  end

  def edit
  end

  def create
    @deck = current_user.decks.new(decks_params)
    if @deck.save
      redirect_to dashboard_root_path
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @deck.update(decks_params)
      redirect_to [:dashboard, @deck]
    else
      render 'edit'
    end
  end

  def destroy
    @deck.destroy
    redirect_to dashboard_decks_path
  end

  private

  def decks_params
    params.require(:deck).permit(:name)
  end

  def set_deck
    @deck = current_user.decks.find_by(id: params[:id])
    redirect_to dashboard_root_path unless @deck
  end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  def index
    rand_card
  end

  def check
    result = CompareOriginText.call(
      params: cards_params
    )
    respond_to do |format|
      format.html { redirect_to :back, notice: result.notice }
      format.js do
        rand_card
        flash.now[:notice] = result.notice
      end
    end
  end

  private

  def rand_card
    result = GetRandomCard.call(
      params: { user_id: current_user.id }
    )
    @card = result.card
  end

  def cards_params
    params.require(:random_card).permit(:original_text, :card_id, :time)
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if login(session_params[:email], session_params[:password])
      redirect_back_or_to(dashboard_root_path, notice: t('.success'))
    else
      flash.now[:alert] = t('.login')
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(dashboard_root_path, notice: t('.exit'))
  end

  private

  def session_params
    params.require(:user_sessions_).permit(:email, :password)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]
  before_action :set_user, only: [:edit, :update, :set_current_deck]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(user_params[:email], user_params[:password])
      redirect_to dashboard_root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to dashboard_root_path
    else
      render 'edit'
    end
  end

  def set_current_deck
    if @user.update_attribute(:deck_id, params[:deck_id])
      redirect_to dashboard_deck_path(params[:deck_id])
    else
      redirect_to dashboard_root_path, notice: t('.wrong')
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :locale)
  end

  def set_user
    @user = User.find(params[:id])
    redirect_to dashboard_root_path unless @user == current_user
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/dashboard/decks/_form.html.erb
<%= simple_form_for [:dashboard, @deck] do |f| %>
	<%= f.input :name %>
	<%= f.button :submit %>
<% end %>

app/views/dashboard/decks/edit.html.erb
<h2><%= t('.deck') %></h2>
<%= render 'form' %>
<%= link_to t('link.main'), dashboard_root_path %>

app/views/dashboard/decks/index.html.erb
<h2><%= t(".decks") %></h2>
<p><%= link_to t('.new_deck'), new_dashboard_deck_path, class: "btn btn-primary" %></p>
<% @decks.each do |deck| %>
	<p>
		<span><%= deck.name %></span>
		<div>
      <%= link_to "#{t('.deck')} | ", dashboard_deck_path(deck) %>
			<%= link_to "#{t('.ed_deck')} | ", edit_dashboard_deck_path(deck) %>
			<%= link_to "#{t('.del_deck')} | " , dashboard_deck_path(deck), method: :delete, 
															  data: { confirm: 'Are you sure?' } %>
      <%= link_to "#{t('.set_curr')}", dashboard_set_deck_path(current_user, deck.id), method: :put %>
		</div>
	</p>
<%end%>

app/views/dashboard/decks/new.html.erb
<h2><%= t('.deck') %></h2>
<%= render 'form' %>
<%= link_to t('link.main'), dashboard_root_path %>

app/views/dashboard/decks/show.html.erb
<h2><%= @deck.name %></h2>
<h3><%= t('.cards') %>:</h3>
<% @deck.cards.each do |card| %>
  <p>
    <span><%= card.original_text %> | </span>
    <span><%= card.translated_text %> | </span>
    <span><%= t('.next_rev') %> <%= card.review_date.strftime("%d/%m/%Y") %></span>
    <div>
      <%= link_to "#{t('.card')} | ",dashboard_card_path(card) %>
      <%= link_to "#{t('.ed_card')} | ", edit_dashboard_card_path(card) %>
      <%= link_to "#{t('.del_card')}" ,dashboard_card_path(card), method: :delete, 
                                data: { confirm: 'Are you sure?' } %>
    </div>
  </p>
<%end%>

<%= link_to t('link.main'), dashboard_root_path %>