config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    namespace :dashboard do
      resources :decks
      resources :cards
      resources :users, only: [:new, :create, :edit, :update]

      put '/users/:id/set_current/:deck_id' => 'users#set_current_deck', :as => 'set_deck'
      root 'home#index'
      post 'home' => 'home#check'
    end

    namespace :home do
      resources :user_sessions, only: [:new, :create, :destroy]
      get 'login' => 'user_sessions#new', :as => :login
      post 'logout' => 'user_sessions#destroy', :as => :logout
    end
  end

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get '/' => 'dashboard/home#index'
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :p, msg, class: "alert-info" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.title') %></title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section id="container">
    <% unless current_user %>
      <%= link_to("ru", dashboard_root_url(locale: :ru), class: "btn btn-default") %>
      <%= link_to("en", dashboard_root_url(locale: :en), class: "btn btn-default") %>
    <% end %>
    <header class="clearfix">
  	  <nav class="navbar navbar-default">
  	      <ul class="nav navbar-nav navigation-links">
  	        <li><%= link_to t('.cards'), dashboard_cards_path %></li>
            <li><%= link_to t('.decks'), dashboard_decks_path %></li>
  	        <li><%= link_to t('.new_card'), new_dashboard_card_path %>
            <% if current_user %>
              <li><%= link_to "#{t('.ed_profile')} #{current_user.email}", edit_dashboard_user_path(current_user.id) %></li>
              <li><%= link_to t('.logout'), :home_logout, method: :post %></li>
            <% else %>
              <li><%= link_to t('.reg'), new_dashboard_user_path %></li>
              <li><%= link_to t('.github'), auth_at_provider_path(:provider => :github, locale: nil) %></li>
              <li><%= link_to t('.enter'), :home_login %></li>
             <% end %>
  	      </ul>
  	  </nav>

      <h1><%= t('.main_title') %></h1>
      <%= link_to t('link.main'), dashboard_root_path %>
    </header>
    <section>
      <div id="notice">
        <%= render :partial => 'layouts/flash' , :locals => { :flash => flash } %>
      </div> 
    	<div id="main_content"><%= yield %></div>
    </section>

  </section>
</body>
</html>